### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by gotev** [Adobe-Marketing-Cloud/acp-sdks#168]
When should we expect support for SPM? Currently using Carthage, but no luck with this SDK yet. Seen you closed a previous issue regarding Carthage support. When not using CocoaPods, is manual import the only option we have? Trying to find a way to at least make a framework out of the static files published here to have a cleaner way to import in projects. Any advice on how to do that?

Thank you :wink:

**Comment by imironchuk** [comment]
Hi @gotev - At this time manual import should be used in iOS projects if not using CocoaPods. We also have ReactNative SDKs that can be fetched through NPM.

**Comment by mcmurrym** [comment]
Please be ready with SPM support by Xcode 11 release date.

**Comment by pfransenadb** [comment]
We're keeping an eye on SPM, but there's currently a few features we'd require before we can move over:

* Lack of binary distribution support - SPM currently doesn't have a way to include closed-source binary distributions as part of a package.  While we're working to move significant portions of our code into the open, it's an involved process that will take time.  This is an [active discussion](https://forums.swift.org/t/spm-support-for-binaries-distribution/25549) on the Swift forums about this, so hopefully we'll see it sooner rather than later.

* Lack of support for non-swift code.  Even if all of our code and dependencies were readily available as open-source, the ACP SDKs for IOS are built from a mixed codebase (namely C++11 and Objective-C).  While it's possible to hack together some scripts to handle the build process, they'd be exceedingly fragile and prone to issues as the SPM ecosystem evolves.  (this also means that even in a full open-source environment, we'd likely still need the binary distribution support mentioned above).

I'll leave this issue open so we can continue to discuss and provide updates.


pete fransen
mobile architect
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)

**Comment by gotev** [comment]
@pfransenadb oh wow, it's a really long and hard road then, good luck! I understand the intricacies of that process. Just wondering if there's a faster way to have an SDK written purely in Swift, without porting the actual one and which could be contributed by the community, too.

AFAIK, an SDK like this in its core intercepts system events and user trackings (trackEvent, trackState) and saves them into a local DB queue. Then you have a spooler which dequeues events and sends them to the cloud by calling some APIs in certain conditions (connection available, max number or persisted events reached, ...). Leveraging keychain you could safely store API keys on the client. I know it's a lot more than this to provide all the features of the current SDK, but if there's a set of public APIs which can be called by apps, it would be great. Also, having only a limited set of features available initially (lifecycle, trackState, trackEvent) would be absolutely fine, as long as it's in Swift, because honestly, in a project using only Swift 5 and Swift dependencies without CocoaPods (preparing for SPM), having a bridging header only for a single SDK and having to import things manually losing the auto update feature from the package manager, feels really old.

**Comment by corteggo** [comment]
Since Xcode 11 adds support for SPM packages with ease this is very important. I totally understand the technical blockers though.

Just wanted to add that we found another project that was using mixed sources and we were able to make it work. Check it out at https://github.com/arturdev/Unrealm/pull/9. So, opening your source code and creating separate targets for each language part would enable you to support SPM.

Let's see how long does it take for Apple to support binary distribution.

**Comment by oscarcv** [comment]
Hi, XCode 12 has launched with SPM and Binary support, Can you make possible generate XCFramework and distribute over Swift Package Manager? 

https://developer.apple.com/documentation/swift_packages/distributing_binary_frameworks_as_swift_packages

**Comment by imironchuk** [comment]
Hi @oscarcv  - We are going to be launching a beta for a new swift based SDK that will use XCFrameworks and SPM. If interested in participating in the beta, please sign-up [here](https://forms.microsoft.com/Pages/ResponsePage.aspx?id=Wht7-jR7h0OUrtLBeN7O4UJN9zAhIEhJr3PBfyMf9wdUQTI2S0pMVEVYS1k3UUNJVDNDWlRUTFk4Qi4u).

**Comment by oscarcv** [comment]
> Hi @oscarcv  - We are going to be launching a beta for a new swift based SDK that will use XCFrameworks and SPM. If interested in participating in the beta, please sign-up [here](https://forms.microsoft.com/Pages/ResponsePage.aspx?id=Wht7-jR7h0OUrtLBeN7O4UJN9zAhIEhJr3PBfyMf9wdUQTI2S0pMVEVYS1k3UUNJVDNDWlRUTFk4Qi4u).

Thx 😁

**Comment by ondrejhanslik** [comment]
We are not really interested in beta of a new SDK.

You are already building the old SDK as xcframeworks. Could you just add that single `Package.swift` file with links to these frameworks?

**Comment by shalehaha** [comment]
Hi all,
Please check out https://github.com/adobe/aepsdk-core-ios, https://github.com/adobe/aepsdk-analytics-ios, https://github.com/adobe/aepsdk-audience-ios. We have finished rewritten some of the extensions in Swift, and are working on the rest of them. Documentation and migration guide will be coming soon as well.
