### ISSUE TITLE
NSPhotoLibraryUsageDescription

### ISSUE THREAD

**Issue by syrotynin** [Adobe-Marketing-Cloud/acp-sdks#183]
Hi, I've added several libraries to the project manually:
ACPCore, ACPMobileServices, ACPTarget, ACPTargetVEC, ACPUserProfile.

When I upload a build to TestFlight I receive an email from Apple:
<img width="814" alt="Screen Shot 2019-07-30 at 2 38 23 PM" src="https://user-images.githubusercontent.com/6272133/62126220-dbfcc780-b2d7-11e9-9de7-1980c3e5660f.png">

Please clarify a purpose of using Photo library.

**Comment by sbenedicadb** [comment]
Hey @syrotynin,

The offending code was found in the ACPTargetVEC extension.  It has been refactored so that it  will no longer cause rejection from Apple.  

Please update to ACPTargetVEC v2.1.0 to fix this issue.  Thank you.

**steve benedick**
*sr mobile software engineer*
[Adobe Experience Cloud](http://www.adobe.com/experience-cloud.html)
