### ISSUE TITLE
Lifecycle event not track on iOS 13

### ISSUE THREAD

**Issue by miquellaboria** [Adobe-Marketing-Cloud/acp-sdks#270]
We are using the last version of the SDK in iOS (4.18.8) and the devices with iOS 13 doesn't track the lifecycle event.

Older versions of SDK  track a CrashEvent when send LifeCycle in iOS 13, in the last version of SDK the event was sent, but visits doesn't appear.

**Comment by shalehaha** [comment]
@miquellaboria 
Can you clarify on `the event was sent, but visits doesn't appear`, do you mean you saw the hits going out from the device, but the report wasn't line up with that?

Also, can you please reach out to the [customer care](https://helpx.adobe.com/marketing-cloud/contact-support.html) and open a ticket. We will need more info like the company name in order to inspect the reports. Thank you.

**Comment by shalehaha** [comment]
Closing the ticket due to inactivity, feel free to reopen if you need more help.
