### ISSUE TITLE
Support for Carthage

### ISSUE THREAD

**Issue by joshfuggle** [Adobe-Marketing-Cloud/acp-sdks#406]
A lot of apps now days use Carthage as their dependency manager of choice, however your repository is limited to CocoaPods.

Can you please extend this repository to support Carthage? It is [quite simple to do](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework).

**Comment by imironchuk** [comment]
Hi @joshfuggle thanks for the +1 on Carthage support. We will consider this for the future. At this time we cannot support Carthage due to the way it handles versions and dependencies. The biggest hurdle in using Carthage is that we distribute the SDK as static libraries, vs dynamic. Also with some of the extensions we have subspecs i.e. tvOS. We are also looking to support Swift Package Manager in the future.

**Comment by CognitiveWin** [comment]
I'd also prefer Carthage but will accept SPM. Presumably this will be in the iOS 14 timeframe? (Not that far away.)

**Comment by hamdshah** [comment]
Any new on Swift package support ?

**Comment by praveek** [comment]
@hamdshah The latest AEP Mobile extensions support SPM, please check this out https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep/current-sdk-versions#ios-swift

**Comment by sbenedicadb** [comment]
the SDK supports manual installation, as well as dependency management tools Cocoapods and SPM (for the AEP SDKs).  

closing this issue as Carthage support is not on an existing roadmap.
