### ISSUE TITLE
ACPIdentity | getExperienceCloudId issue 

### ISSUE THREAD

**Issue by NareshJain91** [Adobe-Marketing-Cloud/acp-sdks#576]
Hi Team, 

I am using ACPIdentity extensionVersion 2.5.1. 

I did ACPIdentity.registerExtension() and then 
ACPCore.configureWithFile(inPath: MyFilePath)
ACPCore.lifecycleStart(["state": "appResume"])
ACPCore.start(nil)

Every time when I am trying to getExperienceCloudId from ACPIdentity, 

I get an error - "Error Domain=com.adobe.marketing.mobile Code=1 "(null)"

**Comment by kevinlind** [comment]
Hi @NareshJain91 

I suspect your request is timing out with error code 1.

In your application logs, do you see this message when calling getExperienceCloudId?
`[AdobeExperienceSDK WARNING <com.adobe.module.identity>]: ProcessEventQueue : Configuration is missing a valid experienceCloud.org which is needed to process Identity events. Processing will resume once a valid configuration is obtained.`

Can you verify that your configuration includes a value for "experienceCloud.org"? The ACPIdentity extension requires an Experience Cloud Organization ID in order to process requests and generate an ECID.

Thank you,
Kevin Lind
