### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by petarlazarov** [Adobe-Marketing-Cloud/acp-sdks#603]
Can you please extend this repository to support SPM?

**Comment by emdobrin** [comment]
Hi @petarlazarov, 

The latest AEP Mobile extensions support SPM, please check this out https://aep-sdks.gitbook.io/docs/resources/upgrading-to-aep/current-sdk-versions#ios-swift

Emilia

**Comment by GeorgiDamyanov** [comment]
Hi @emdobrin, is there a plan to have SPM support for the AEPMobileServices extension? It appears that it is only available as an .xcframework binary and I cannot get this to work with the remaining extensions being distributed as SPM dependencies.

**Comment by ahmyr** [comment]
We do not plan to add SPM support for AEPMobileServices as it will be end-of-life next year:
https://experienceleague.adobe.com/docs/mobile-services/using/eol.html?lang=en

We do plan to add tvOS support, but no ETA on it yet.

**Comment by ahmyr** [comment]
@GeorgiDamyanov, what errors/issues are you seeing when trying to use the AEPMobileServices .xcframework binary with the other SPM extensions. You should be able to do that.

**Comment by anlosar** [comment]
I can't get it to work either. AEPCore import in AEPMobileServices.h shows an error indicating module not found.

**Comment by cdhoffmann** [comment]
Closing, as we will not be adding SPM support for AEPMobileServices as it will be end-of-life next year: https://experienceleague.adobe.com/docs/mobile-services/using/eol.html?lang=en. If you would like to use AEPMobileServices until then, we recommend using Cocoapods instead of SPM, or use XCFrameworks for all of the AEP libraries.
