### ISSUE TITLE
AEPMobileServices v3.0.3 missing module.modulemap

### ISSUE THREAD

**Issue by markph0204** [Adobe-Marketing-Cloud/acp-sdks#689]
The latest version is missing this important file to find header file.

It was included in v3.0.0, so I borrowed and updated my copy of v3.0.3 with the **module.modulemap** from v.3.0.0 and so far its working.

**Comment by cdhoffmann** [comment]
Hey @markph0204. AEPMobileServices has been end-of-life since end of last year. More info about that can be found [here](https://experienceleague.adobe.com/docs/mobile-services/using/home.html?lang=en). We recommend using our new AEP extensions found [here](https://developer.adobe.com/client-sdks/documentation/current-sdk-versions/#ios-beta-testing).
