### ISSUE TITLE
Android - Provide BOM

### ISSUE THREAD

**Issue by SebRut** [Adobe-Marketing-Cloud/acp-sdks#692]
It would be nice if you could release a `com.adobe.marketing.mobile:bom` BOM artifact like for example  [Compose BOM](https://developer.android.com/jetpack/compose/bom) and [Firebase](https://firebase.google.com/docs/android/learn-more?hl=en#bom). This would allow us to easily update the sdk without having to worry about using incompatible versions of dependencies.

**Comment by yangyansong-adbe** [comment]
Hi @SebRut , we're still working on the BOM artifact for Adobe mobile SDKs. The GA release is coming soon. I will let you know once the GA build is released. 

Thanks,
Yansong

**Comment by yangyansong-adbe** [comment]
Close this issue because the BOM artifact for Adobe Android SDKs was released. @SebRut, please take a look at the [release notes](https://developer.adobe.com/client-sdks/documentation/release-notes/#android-bom-100). We are currently working on some UI and documentation changes. However, if you already understand how to use the BOM artifact, you can start using it in your Android projects. If you have any future questions, please don't hesitate to reach out. 


Thanks,
Yansong
