### ISSUE TITLE
Lack of education on ACPTargetRequestObject

### ISSUE THREAD

**Issue by evidana** [Adobe-Marketing-Cloud/acp-sdks#88]
Curious how to write the following request with the optional callback param that is included in the docs.

`var targetRequest = ACPTargetRequestObject(name: "mboxName", defaultContent: "duh", mboxParameters: ["test": "true"])`

Keep getting caught up in what that callback function is wanting. I wish this made sense to me:

`@property(nonatomic, strong, nullable) void (^callback)(NSString* __nullable content); ///< Optional. When batch requesting Target locations, callback will be invoked when content is available for this location.
@end`

could you provide an example?

**Comment by rymorale** [comment]
The Target Request with optional callback can be written like:
`var callbackData = ""
var request = ACPTargetRequestObject(name: "mboxName", defaultContent: "duh", mboxParameters: ["test":"true"], callback: {(_ content: String?) -> Void in
               callbackData = content
        })`
Each target request object defined will have its own callback defined and after ACPTarget.loadRequests is called and content is available, each callback will contain the data loaded from Target. Otherwise, the default content is used.

**Comment by evidana** [comment]
Thanks for the help. One more question:

`
let request = ACPTargetRequestObject(name: "mboxName", defaultContent: "duh", mboxParameters: ["test":"true"], callback: {(_ content: String?) -> Void in
                callbackData = content!
        })
`

The editor was only happy with content having an exclamation at the end. Otherwise, it was throwing Value of optional type 'String?' must be unwrapped to a value of type 'String'. Does that make sense? Or is there some other change that fits better?

**Comment by rymorale** [comment]
This is because the callback value is "nullable" in the Objective-c SDK code and we need to use the exclamation point to unwrap the value it returns when used in Swift. More info can be seen at https://developer.apple.com/swift/blog/?id=25. Using the exclamation is fine and I just missed it in my code sample above.

**Comment by evidana** [comment]
Thanks!
